---
title: "c0183_vv"
date: 2020-10-07T00:11:33+1010:00
draft: false
weight: 11831

---

### Log reference: <no value>

```
    loading [Config]:  ./tests/functests/upconfig.yml
    Main config:
                 Version -> 1.0.0
                  RefDir -> ./tests/functests
                 WorkDir -> cwd
              AbsWorkDir -> /up_project/up
                TaskFile -> c0183
                 Verbose -> vv
              ModuleName -> self
               ShellType -> /bin/sh
           MaxCallLayers -> 8
                 Timeout -> 3600000
     MaxModuelCallLayers -> 256
               EntryTask -> task
      ModRepoUsernameRef -> 
      ModRepoPasswordRef -> 
    work dir: /up_project/up
    -exec task: task
    loading [Task]:  ./tests/functests/c0183
    module: [self], instance id: [dev], exec profile: []
    Task1: [task ==> task:  ]
    -Step1: [
    expect sub_task to close file each time in loop iteration
    ]
    =Task2: [task ==> sub_task: without rescue, the execution will return a non-zero  return code in shell and also report the error
    with rescue, the program will return 0
     ]
    --Step1: [step1: step 1 ]
    cmd( 1):
    echo "opening file"
    
    -
    opening file
    
    -
     .. ok
    cmd( 2):
    echo "hello"|grep "world"
    
    -
    
    -
     .. failed(suppressed if it is not the last step)
     WARN: [ignoreError:] - [Error ignored!!!]
    --Step2: [
    step2in this case, since there is no ignoreError, the exception was captured by task level finaly code block
    opened file is safely closed
    to make the flow to continue to reach step2, use ignoreError
    ]
    ~~SubStep1: [print:  ]
    step 2
    task Finally:
    -Step1: [
    close_fileensure the opened file is closed
    ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
    =Task2: [task ==> sub_task: without rescue, the execution will return a non-zero  return code in shell and also report the error
    with rescue, the program will return 0
     ]
    --Step1: [step1: step 1 ]
    cmd( 1):
    echo "opening file"
    
    -
    opening file
    
    -
     .. ok
    cmd( 2):
    echo "hello"|grep "world"
    
    -
    
    -
     .. failed(suppressed if it is not the last step)
     WARN: [ignoreError:] - [Error ignored!!!]
    --Step2: [
    step2in this case, since there is no ignoreError, the exception was captured by task level finaly code block
    opened file is safely closed
    to make the flow to continue to reach step2, use ignoreError
    ]
    ~~SubStep1: [print:  ]
    step 2
    task Finally:
    -Step1: [
    close_fileensure the opened file is closed
    ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
    
```

##### Logs with different verbose level
* [c0183 log - verbose level v](../../logs/c0183_v)
* [c0183 log - verbose level vv](../../logs/c0183_vv)
* [c0183 log - verbose level vvv](../../logs/c0183_vvv)
* [c0183 log - verbose level vvvv](../../logs/c0183_vvvv)
* [c0183 log - verbose level vvvvv](../../logs/c0183_vvvvv)

##### References
* [Related Chapter](../../flow-controll/c0183)
