---
title: "c0184_vv"
date: 2020-09-18T01:27:57+99:00
draft: false
weight: 11841

---

### Log reference: <no value>

```
    loading [Config]:  ./tests/functests/upconfig.yml
    Main config:
                 Version -> 1.0.0
                  RefDir -> ./tests/functests
                 WorkDir -> cwd
              AbsWorkDir -> /up_project/up
                TaskFile -> c0184
                 Verbose -> vv
              ModuleName -> self
               ShellType -> /bin/sh
           MaxCallLayers -> 8
                 Timeout -> 3600000
     MaxModuelCallLayers -> 256
               EntryTask -> task
    work dir: /up_project/up
    -exec task: task
    loading [Task]:  ./tests/functests/c0184
    module: [self], instance id: [dev], exec profile: []
    Task1: [task ==> task:  ]
    -Step1: [: task ]
    -Step1:
    =Task2: [task ==> sub_task_layer1: sub_task_layer1 ]
    --Step1:
    ==Task3: [task/sub_task_layer1 ==> sub_task_layer2: without rescue, the execution will return a non-zero  return code in shell and also report the error
    with rescue, the program will return 0
     ]
    ---Step1: [step1: step 1 ]
    cmd( 1):
    echo """opening file: {{.loopitem}}"""
    
    -
    opening file: item1
    
    -
     .. ok
    cmd( 2):
    echo "hello"|grep "world"
    
    -
    
    -
     .. failed(suppressed if it is not the last step)
     WARN: [ignoreError:] - [Error ignored!!!]
    ---Step2: [step2: in this case, since there is no ignoreError, the exception was captured by task level finaly code block
    opened file is safely closed
    to make the flow to continue to reach step2, use ignoreError
     ]
    ~~~SubStep1: [print:  ]
    step 2
    task Finally:
    --Step1: [close_file: ensure the opened file is closed
     ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
    ==Task3: [task/sub_task_layer1 ==> sub_task_layer2: without rescue, the execution will return a non-zero  return code in shell and also report the error
    with rescue, the program will return 0
     ]
    ---Step1: [step1: step 1 ]
    cmd( 1):
    echo """opening file: {{.loopitem}}"""
    
    -
    opening file: item2
    
    -
     .. ok
    cmd( 2):
    echo "hello"|grep "world"
    
    -
    
    -
     .. failed(suppressed if it is not the last step)
     WARN: [ignoreError:] - [Error ignored!!!]
    ---Step2: [step2: in this case, since there is no ignoreError, the exception was captured by task level finaly code block
    opened file is safely closed
    to make the flow to continue to reach step2, use ignoreError
     ]
    ~~~SubStep1: [print:  ]
    step 2
    task Finally:
    --Step1: [close_file: ensure the opened file is closed
     ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
    
```

##### Logs with different verbose level
* [c0184 log - verbose level v](../../logs/c0184_v)
* [c0184 log - verbose level vv](../../logs/c0184_vv)
* [c0184 log - verbose level vvv](../../logs/c0184_vvv)
* [c0184 log - verbose level vvvv](../../logs/c0184_vvvv)
* [c0184 log - verbose level vvvvv](../../logs/c0184_vvvvv)

##### References
* [Related Chapter](../../flow-controll/c0184)
