---
title: "f0178_v"
date: 2020-08-18T15:16:30+88:00
draft: false
weight: 11780

---

### Log reference: <no value>

```
    loading [Config]:  ./tests/functests/upconfig.yml
    Main config:
                 Version -> 1.0.0
                  RefDir -> ./tests/functests
                 WorkDir -> cwd
              AbsWorkDir -> /up_project/up
                TaskFile -> f0178
                 Verbose -> v
              ModuleName -> self
               ShellType -> /bin/sh
           MaxCallLayers -> 8
                 Timeout -> 3600000
     MaxModuelCallLayers -> 256
    work dir: /up_project/up
    -exec task: task
    loading [Task]:  ./tests/functests/f0178
    module: [self], instance id: [dev], exec profile: []
    Task1: [task ==> task:  ]
    -Step1:
    cmd( 1):
    -
    executing workflow .......
    step 1 .......
    step m .......
    encountering an error ......
    error 1 ......
    error 2 ......
    ./tests/functests/mock_error.sh: exit: line 11: Illegal number: -1
    -
     .. failed(suppressed if it is not the last step)
     WARN: [Not rescued in task level] - [please assess the panic problem and cause, fix it before re-run the task]
    task finally ->   ERROR: Failed And Not Ignored! [You may want to continue and ignore the error]
    
    
```

##### Logs with different verbose level
* [f0178 log - verbose level v](../../logs/f0178_v)
* [f0178 log - verbose level vv](../../logs/f0178_vv)
* [f0178 log - verbose level vvv](../../logs/f0178_vvv)
* [f0178 log - verbose level vvvv](../../logs/f0178_vvvv)
* [f0178 log - verbose level vvvvv](../../logs/f0178_vvvvv)

##### References
* [Related Chapter](../../shell-func/f0178)
